import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home Page By NextJs , Typescript and Tailwind-CSS</h1>
      {/* {Header} */}
      <main>
        {/* Banner */}
        <section>
          
        </section>
      </main>
    </div>
  );
};

export default Home;
